version: '3.9'
services: 
  dash: 
    image: thassung/demoapp:v1.0.4
    build:
      context: .
      dockerfile: dash.Dockerfile
    volumes:
      - ./.vscode-server:/root/.vscode-server
      - ./code:/root/code
    ports:
      - 9999:8050
    command: ["python", "app.py"]
.